### ISSUE TITLE
Copyright information inconsistent in roadmap

### ISSUE THREAD

**Issue by breimann** [ktrue/proclaim-utility#2]
Hi ktrue,

I've been using the proclaim utility and it's been fantastic.

There is one thing i've noticed, it's that the copyright info (eg. words, music attribution, copyright info and our ccli number) is inconsistently coming out in the worship roadmap.

Often the first song has very little information, then some of the later songs have more??

So i'm just wondering where in the php files that bit is mentioned, and I could force it to put the information we wish?

Or do you have any idea why this is happening at all?

ie. author, copyright, ccli number (ours).

I've edited settings file with our church name, ccli number etc. We don't have a OneLicense.net number.

Does this make sense?

**Comment by ktrue** [comment]
The attributions for a Lyrics slide are all from what you put in the Copyright area and whether you've checked the CCLI box (and have your CCLI license number filled in).

The Settings file only customizes the mini-website so it doesn't have to know your CCLI number, song number or other details regarding the Proclaim slide set .. just where (on the website) it can be uploaded and processed by roadmap.php.

The roadmap.php just reads the JSON of the slide set to produce all that is displayed.  Each Lyrics slide has areas for inserting author, copyright, hymnal, and CCLI status/song number/license number.  That data in the Lyrics slide is kept in the Proclaim backup .prs file and 'teased-out' by the roadmap.php program for display.

Here's 3 samples showing what I mean.  A CCLI song, a non-CCLI song (with OneLicense attribution in the copyright area) and how it shows on the roadmap.php?summary

### CCLI Song
![CCLI song](https://user-images.githubusercontent.com/17507343/219228278-b0898dbb-0781-454b-809c-e534b6f937f3.jpg)

### Song from Hymnal
![NonCCLI song](https://user-images.githubusercontent.com/17507343/219228280-7cdecb60-1892-4921-b6fc-cc71e1f21306.jpg)

### roadmap.php?summary display
![Roadmap Summary](https://user-images.githubusercontent.com/17507343/219228276-fb06f21e-ebf9-491f-aeb1-11c6938f7c9b.jpg)

If you can attach a copy of your Proclaim slide backup to an email to me ( webmaster[at]campbellucc.org ) I'd be glad to take a look.

Hope this helps...

**Comment by breimann** [comment]
Thank you ktrue, sorry for the delay, i've had a bit going on.

So I'll email you a current .prs backup for our 8.30am service this coming sunday.

**Comment by ktrue** [comment]
Thanks for sending the Proclaim Slide backup.  I noticed that the Credits part for SongLyrics wasn't being processed by the roadmap.php script, so I added the code to display that (if it is non-blank).  Now the credits show as Credit; Copyright when both exist and just Copyright when no Credit.
Thanks for spotting the issue.
